//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSVID_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDiem
    {
        public int ID { get; set; }
        public int IDDiem { get; set; }
        public string LoaiDiem { get; set; }
        public Nullable<double> Diem { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
