//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSVID_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HocPhan
    {
        public int ID { get; set; }
        public string TenHocPhan { get; set; }
        public int IDSV { get; set; }
        public Nullable<int> SoTinChi { get; set; }
        public Nullable<int> HeSo { get; set; }
        public Nullable<int> Ky { get; set; }
        public string NamHoc { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
