//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSVID_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichHoc
    {
        public int ID { get; set; }
        public Nullable<int> IDSV { get; set; }
        public string Tuan { get; set; }
        public string Ngay { get; set; }
        public string Thu { get; set; }
        public string Tiet { get; set; }
        public string ThoiGian { get; set; }
        public Nullable<int> IdHP { get; set; }
        public string Phong { get; set; }
        public string GiaoVien { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
