//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSVID_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien
    {
        public int ID { get; set; }
        public string MatKhau { get; set; }
        public string HoTen { get; set; }
        public string NgaySinh { get; set; }
        public string NganhHoc { get; set; }
        public string Lop { get; set; }
        public string KhoaHoc { get; set; }
        public string Avatar { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
